/* DO NOT EDIT THIS FILE - it is machine generated */
#include "include\jni.h"
/* Header for class beepJNI */

#ifndef _Included_beepJNI
#define _Included_beepJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     beepJNI
 * Method:    beep
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_beepJNI_beep
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
